### ISSUE TITLE
SearchResultView still doesn’t occur.

### ISSUE THREAD

**Issue by BohaoZhao777** [wwddddnnn/CSC207-API#13]
After getting the recipes from API successfully, the SearchResultView still doesn’t occur.
Try to rewrite the prepareSuccessView — failed
The viewName in the SearchResultView was wrong. Search Result → Search results.
The files that cause issues is folloing:
src/view/SearchResultView
src/interfacte_adaptet/search_recipe/SearchPresenter

**Comment by wwddddnnn** [comment]
The viewName in the SearchResultView was wrong. Search Result → Search results.
